# Generated by Django 4.0.4 on 2022-07-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0002_alter_customusers_managers_alter_customusers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='is_staff',
        ),
    ]
