# Generated by Django 4.0.4 on 2022-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0004_customusers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': 'length is not acceptable '}, help_text='your phone number will be used to authenticate you next time +989121111111', max_length=20, null=True, unique=True),
        ),
    ]
