# Generated by Django 4.0.4 on 2022-07-12 15:55

import customusers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0005_alter_customusers_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='is_whore',
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='is a vip'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='re_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': 'length is not acceptable ', 'unique': 'phone already exists.'}, help_text='your phone number will be used to authenticate you next time +989121111111', max_length=20, null=True, unique=True, validators=[customusers.validators.PhoneValidator()]),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(error_messages={'max_length': 'length is not acceptable'}, help_text='200 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=200, validators=[customusers.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
