# Generated by Django 4.0.4 on 2022-07-12 16:27

import customusers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0006_remove_customusers_is_whore_customusers_is_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[customusers.validators.FirstNameValidator], verbose_name='first name'),
        ),
    ]
