# Generated by Django 4.0.4 on 2022-07-12 16:39

import customusers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0007_alter_customusers_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='password',
            field=models.CharField(max_length=128, validators=[customusers.validators.CheckPasswords], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='re_password',
            field=models.CharField(blank=True, max_length=128, validators=[customusers.validators.CheckPasswords]),
        ),
    ]
