# Generated by Django 4.0.4 on 2022-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0008_alter_customusers_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='re_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
