# Generated by Django 4.0.4 on 2022-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_contactmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
