# Generated by Django 4.0.4 on 2022-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drf', '0002_alter_contactmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
