# Generated by Django 4.0.4 on 2022-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drf', '0002_blogmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
